parameters:
- name: environment
  type: string
- name: dependsOn
  type: string

stages:
  - ${{ if or(and(eq(parameters['environment'], 'Prod'), not(eq(variables['Build.SourceBranchName'], 'master'))), eq(variables['Build.SourceBranchName'],'master')) }}:
    - stage: "DeployTo${{ parameters.environment }}"
      ${{ if ne(parameters['environment'], 'Prod') }}:
        environment: 'nonprod'
      ${{ if eq(parameters['environment'], 'Prod') }}:
        environment: 'PROD'
      dependsOn: ${{ parameters.dependsOn }}
      jobs:
      - job: B1
        steps:
        - bash: echo "Hello world"
